### ISSUE TITLE
AttributeError: module 'selectors' has no attribute 'SelectSelector'

### ISSUE THREAD

**Issue by johhenrik** [bernardorufino/pick#17]
I get this error, running on macOS 10.13.3

Henriks-MacBook-Pro-7:pick hj$ ls -l | pick
Traceback (most recent call last):
  File "/Users/hj/git/pick/src/pick.py", line 8, in <module>
    from output_processors.list_processor import ListProcessor
  File "/Users/hj/git/pick/src/output_processors/list_processor.py", line 4, in <module>
    from utils import printstr, writestr
  File "/Users/hj/git/pick/src/utils.py", line 1, in <module>
    import subprocess
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 155, in <module>
    _PopenSelector = selectors.SelectSelector
AttributeError: module 'selectors' has no attribute 'SelectSelector'

This is from installing the source. Using homebrew, it works though.

**Comment by au-phiware** [comment]
This might be related to the version of python being used... have you tried python2?

**Comment by grobi-san** [comment]
Even though this is old now: I encountered a similar problem with another module (_Dash_) and it turned out that a `.py` file in my project with the name `selectors.py` confused the search for the proper `selectors.py` file as required by _Dash_. This makes sense regarding the error message: my own `selectors.py` does not contain a symbol `SelectSelector`. Renaming my own `selectors.py` resolved the issue.
